### ISSUE TITLE
Unable to configure the mailhog http-server port (8025?)

### ISSUE THREAD

**Issue by JayDijkstra** [lando/mailhog#7]
Good day,

I have an issue regarding the HTTP-webserver of the mailhog service. Within the documentation it is clear how to portforward the actual SMTP port, but afaik there is nothing documented how to set the actual MAILHOG_URL to port 8025. This means that when I start the lando configuration, the mailhog url is always listening on a high port: `http://localhost:49264`, is it possible to assign the webserver to http://localhost:8025??

**My Configuration**:

```
mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
```      
Fyi: I did try to configure the ports as follows:

```
ports:
    - 1025:1025
    - 8025:8025
```

But this did not resolve my issue.

Kind Regards!
